#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cloudpickle
Version  : 0.5.2
Release  : 3
URL      : https://pypi.python.org/packages/4d/f5/ee2cb38a72085a1a775812a7d000125aa3096555cafb97d137960d46b7af/cloudpickle-0.5.2.tar.gz
Source0  : https://pypi.python.org/packages/4d/f5/ee2cb38a72085a1a775812a7d000125aa3096555cafb97d137960d46b7af/cloudpickle-0.5.2.tar.gz
Summary  : Extended pickling support for Python objects
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cloudpickle-python3
Requires: cloudpickle-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# cloudpickle
[![Build Status](https://travis-ci.org/cloudpipe/cloudpickle.svg?branch=master
)](https://travis-ci.org/cloudpipe/cloudpickle)
[![codecov.io](https://codecov.io/github/cloudpipe/cloudpickle/coverage.svg?branch=master)](https://codecov.io/github/cloudpipe/cloudpickle?branch=master)

%package python
Summary: python components for the cloudpickle package.
Group: Default
Requires: cloudpickle-python3

%description python
python components for the cloudpickle package.


%package python3
Summary: python3 components for the cloudpickle package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cloudpickle package.


%prep
%setup -q -n cloudpickle-0.5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515336547
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
